DROP USER PROYECTO CASCADE;
CREATE USER PROYECTO IDENTIFIED BY PROYECTO;
GRANT CONNECT,RESOURCE,dba TO PROYECTO;
GRANT UNLIMITED TABLESPACE TO PROYECTO;
ALTER PROFILE DEFAULT LIMIT PASSWORD_REUSE_TIME UNLIMITED;
ALTER PROFILE DEFAULT LIMIT PASSWORD_LIFE_TIME UNLIMITED;

CONNECT PROYECTO/PROYECTO@LOCALHOST:1521/XEPDB1


--ALTER USER PROYECTO ACCOUNT UNLOCK;
--ALTER USER PROYECTO IDENTIFIED BY 12345678;
